spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: jt-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDerializer
      value-deserializer: org.springframework.kafka.support.serializer.jsonDeserializer
      properties:
         spring:
            json:
               trusted:
                 packages: com.javatechie.dto
      
server:
  port: 9292      